"""Create data tables

Revision ID: ecefef0a7f3c
Revises: 4b13a390712f
Create Date: 2025-06-03 18:36:35.397801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecefef0a7f3c'
down_revision: Union[str, None] = '4b13a390712f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercializations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercializations_category'), 'commercializations', ['category'], unique=False)
    op.create_index(op.f('ix_commercializations_id'), 'commercializations', ['id'], unique=False)
    op.create_index(op.f('ix_commercializations_year'), 'commercializations', ['year'], unique=False)
    op.create_table('exportations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grape_type', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exportations_grape_type'), 'exportations', ['grape_type'], unique=False)
    op.create_index(op.f('ix_exportations_id'), 'exportations', ['id'], unique=False)
    op.create_index(op.f('ix_exportations_year'), 'exportations', ['year'], unique=False)
    op.create_table('importations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grape_type', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_importations_grape_type'), 'importations', ['grape_type'], unique=False)
    op.create_index(op.f('ix_importations_id'), 'importations', ['id'], unique=False)
    op.create_index(op.f('ix_importations_year'), 'importations', ['year'], unique=False)
    op.create_table('processings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grape_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processings_grape_type'), 'processings', ['grape_type'], unique=False)
    op.create_index(op.f('ix_processings_id'), 'processings', ['id'], unique=False)
    op.create_index(op.f('ix_processings_year'), 'processings', ['year'], unique=False)
    op.create_table('productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productions_id'), 'productions', ['id'], unique=False)
    op.create_index(op.f('ix_productions_year'), 'productions', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productions_year'), table_name='productions')
    op.drop_index(op.f('ix_productions_id'), table_name='productions')
    op.drop_table('productions')
    op.drop_index(op.f('ix_processings_year'), table_name='processings')
    op.drop_index(op.f('ix_processings_id'), table_name='processings')
    op.drop_index(op.f('ix_processings_grape_type'), table_name='processings')
    op.drop_table('processings')
    op.drop_index(op.f('ix_importations_year'), table_name='importations')
    op.drop_index(op.f('ix_importations_id'), table_name='importations')
    op.drop_index(op.f('ix_importations_grape_type'), table_name='importations')
    op.drop_table('importations')
    op.drop_index(op.f('ix_exportations_year'), table_name='exportations')
    op.drop_index(op.f('ix_exportations_id'), table_name='exportations')
    op.drop_index(op.f('ix_exportations_grape_type'), table_name='exportations')
    op.drop_table('exportations')
    op.drop_index(op.f('ix_commercializations_year'), table_name='commercializations')
    op.drop_index(op.f('ix_commercializations_id'), table_name='commercializations')
    op.drop_index(op.f('ix_commercializations_category'), table_name='commercializations')
    op.drop_table('commercializations')
    # ### end Alembic commands ###
